### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by johntom** [continuous-software/node-authorize-net#7]
Hi,

I just wrote version 1 of johntom/machinepack-authorizenet (see http://node-machine.org/implementing/Getting-Started) but I'm a little confused with the authorize.net versions.
The following works for me (0.0.5) https://www.npmjs.com/package/node-authorize-net along with https://tonicdev.com/npm/node-authorize-net 
my code
```
var service=require('node-authorize-net')(inputs.apiLoginId,inputs.transactionKey);
Service.authCaptureTransaction(inputs.amount,inputs.cardnumber,inputs.cardexpyear,inputs.cardexpmonth,inputs.cardcode).then(function (transaction) {
```

I follow link to github and get https://github.com/continuous-software/node-authorize-net  install authorize.net which is version 1.0.0 and get error codes when trying to use
```
   var AuhorizeNet = require('authorize-net');
      var client = new AuthorizeNet({
        API_LOGIN_ID: inputs.apiLoginId,
        TRANSACTION_KEY: inputs.transactionKey
      });
    
    errors:

The machine triggered its error exit and returned a value:
   ReferenceError: AuthorizeNet is not defined
    at Object.module.exports.fn (C:\a\machinepack-authorizenet\machines\create-t
ransaction-request.js:64:23)
    at _runMachine (C:\a\machinepack-authorizenet\node_modules\machine\lib\Machi
ne.prototype.exec.js:402:17)
    at afterCacheLookup (C:\a\machinepack-authorizenet\node_modules\machine\lib\
Machine.prototype.exec.js:413:7)
    at _cacheLookup (C:\a\machinepack-authorizenet\node_modules\machine\lib\Mach
ine.prototype.exec.js:193:25)
    at Machine_prototype_exec [as exec] (C:\a\machinepack-authorizenet\node_modu
les\machine\lib\Machine.prototype.exec.js:244:5)
    at Object.module.exports.fn (C:\Users\john\AppData\Roaming\npm\node_modules\
machinepack\node_modules\machinepack-localmachinepacks\node_modules\machinepack-
machines\machines\run-instantiated-machine.js:121:21)
    at _runMachine (C:\Users\john\AppData\Roaming\npm\node_modules\machinepack\n
ode_modules\machine\lib\Machine.prototype.exec.js:416:17)
    at afterCacheLookup (C:\Users\john\AppData\Roaming\npm\node_modules\machinep
ack\node_modules\machine\lib\Machine.prototype.exec.js:427:7)
    at _cacheLookup (C:\Users\john\AppData\Roaming\npm\node_modules\machinepack\
node_modules\machine\lib\Machine.prototype.exec.js:199:25)
    at Machine_prototype_exec [as exec] (C:\Users\john\AppData\Roaming\npm\node_
modules\machinepack\node_modules\machine\lib\Machine.prototype.exec.js:250:5)
    at Object.module.exports.fn (C:\Users\john\AppData\Roaming\npm\node_modules\
machinepack\node_modules\machinepack-localmachinepacks\machines\run-machine.js:9
0:8)
    at _runMachine (C:\Users\john\AppData\Roaming\npm\node_modules\machinepack\n
ode_modules\machine\lib\Machine.prototype.exec.js:416:17)
    at afterCacheLookup (C:\Users\john\AppData\Roaming\npm\node_modules\machinep
ack\node_modules\machine\lib\Machine.prototype.exec.js:427:7)
    at _cacheLookup (C:\Users\john\AppData\Roaming\npm\node_modules\machinepack\
node_modules\machine\lib\Machine.prototype.exec.js:199:25)
    at Machine_prototype_exec [as exec] (C:\Users\john\AppData\Roaming\npm\node_
modules\machinepack\node_modules\machine\lib\Machine.prototype.exec.js:250:5)
    at Object.Machine.build.exec.success (C:\Users\john\AppData\Roaming\npm\node
_modules\machinepack\node_modules\machinepack-localmachinepacks\machines\run-mac
hine-interactive.js:206:12)
```
Thanks,
John

**Comment by lorenzofox3** [comment]
Hi,

you need first to install the package running 
```npm install authorize-net```
create you client:

```
var AuhorizeNet = require('authorize-net');
var client = new AuthorizeNet({
  API_LOGIN_ID: '<PLACEHOLDER>',
  TRANSACTION_KEY: '<PLACEHOLDER>'
});
```

then the npm page is a bit confusing, if you want the detailed api go to the [base gateway definition](https://github.com/continuous-software/42-cent-base)

**Comment by Horizon88** [comment]
does react process amex? I had a customer complain that his amex card
turned the widget on the checkoutpage red and couldn't process

NOTICE: This communication is meant only for the addressee(s) named above
and may contain information which is confidential and/or legally
privileged. If you are not the named addressee(s), or the agent responsible
for receiving and delivering this communication to the named addressee(s),
this communication has been sent to you in error. Unauthorised
dissemination, distribution, copying or reliance on this communication is
prohibited and may attract criminal penalties. This message is off the
record and confidential unless we agree otherwise. Thank you.

**Comment by johntom** [comment]
Sorry I wasn't clear but I did an npm install  node.authorize.net and npm install authorize-net. The error reported above is what I get after having installed and tested with code provided. The node.authorize.net sample code works fine.

**Comment by lorenzofox3** [comment]
Sorry. 

[this package](https://www.npmjs.com/package/node-authorize-net) is deprecated in favor of [this one](https://www.npmjs.com/package/authorize-net) which is version 1.0.6. 

Now looking at the stack trace, it looks like the error comes from create-transaction-request.js (an undefined variable) which is not part of this module

**Comment by johntom** [comment]
Hi,
Just successfully tested "try it out" at authorize-net @1.0.6.
Thanks for your prompt attention, much appreciated.
John
